name: release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: release
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
